spring.application.name=GDP

# Configuration de la datasource (valeurs injectées via variables d'environnement, voir .env.example)
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver


# Configuration JPA/Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update  
spring.jpa.show-sql=true  
spring.jpa.properties.hibernate.format_sql=true

#jwt parameters
jwt.secret=BUdBp8awL4WtcXUHFyuR+xefzFhzg6RUB40MOTEwTwlFJk2eOIdsBQCb/F2PzJTmZBQYIazw+bVAo7hUM+8iEg==
jwt.expiration=3600000

#dns frontend
url.front=http://localhost:3000

# Pour que SameSite=Strict fonctionne
server.servlet.session.cookie.same-site=strict

#OpenApi swagger (set false in prod)
springdoc.api-docs.enabled=true