name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:  
  checks: write
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: 'maven'
    
    #- name: Cache Maven
    #  uses: actions/cache@v4
    #  with:
    #    path: ~/.m2
    #    key: ${{ runner.os }}-m2-${{ hashFiles('GDP/**/pom.xml') }}
    #    restore-keys: |               
    #      ${{ runner.os }}-m2-

    - name: Verify Docker is available (required by Testcontainers)
      run: |
        docker info
      #  docker pull hello-world

    - name: Unit Test avec Maven et JaCoCo
      run: mvn -U test jacoco:report -f GDP/pom.xml -B --no-transfer-progress

    - name: Integration tests 
      run: mvn -f GDP/pom.xml -B --no-transfer-progress failsafe:integration-test failsafe:verify
      env:
        DOCKER_HOST: unix:///var/run/docker.sock
        TESTCONTAINERS_RYUK_DISABLED: "false"   
        TESTCONTAINERS_CHECKS_DISABLE: "false"  
    
    - name: Publish Test Report
      uses: dorny/test-reporter@v1
      continue-on-error: true
      if: success() || failure()
      with:
        name: "Tests Spring Boot GDP"
        path: "GDP/target/surefire-reports/TEST-*.xml,GDP/target/failsafe-reports/TEST-*.xml"
        reporter: "java-junit"
        fail-on-error: false   

    - name: JaCoCo Coverage Report
      id: jacoco
      uses: PavanMudigonda/jacoco-reporter@v5.0
      with:
        coverage_results_path: GDP/target/site/jacoco/jacoco.xml
        coverage_report_name: "Coverage"
        github_token: ${{ secrets.GITHUB_TOKEN }}
        #minimum_coverage: 70  
        #fail_below_threshold: false